#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
HISTSIZE=130000
SAVEHIST=130000

alias ec='TERM=screen-256color emacsclient'

# https://fb.facebook.com/groups/hack.of.the.day/permalink/767242569991027/
# Example: `bscomm fbgs foo bar` finds files which contain both foo and bar
bscomm() {
  cmd=$1
  shift

  result=$($cmd -l $1 | sort -u)
  shift
  for q in $@; do
    result=$(comm -12 <(echo "${result}") <($cmd -l $q | sort -u))
  done
  echo "${result}"
}

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{089} ${bld_on}λ${bld_off} %f%k%F{white}%f "
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='246'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='246'
POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND='246'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='155'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='155'

osconfig="${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc-$(uname).zsh"
if [[ -s "${osconfig}" ]]; then
  source "${osconfig}"
fi
