
alias ls=exa

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{089}%F{white} ${bld_on}λ${bld_off} %f%k%F{089}%f "
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BACKGROUND='grey'
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND='white'
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true
